name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080
          - 8081:8081
          - 8082:8082
          - 8083:8083
          - 8084:8084
          - 8085:8085
          - 8086:8086
          - 8161:8161
          - 61616:61616

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ActiveMQ image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/activemq:latest ./activemq
          docker push ${{ secrets.DOCKER_USERNAME }}/activemq:latest

      - name: Build and push Bank1 image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bank1:latest ./bank1
          docker push ${{ secrets.DOCKER_USERNAME }}/bank1:latest

      - name: Build and push Bank2 image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bank2:latest ./bank2
          docker push ${{ secrets.DOCKER_USERNAME }}/bank2:latest

      - name: Build and push Bank3 image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bank3:latest ./bank3
          docker push ${{ secrets.DOCKER_USERNAME }}/bank3:latest

      - name: Build and push Bank4 image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bank4:latest ./bank4
          docker push ${{ secrets.DOCKER_USERNAME }}/bank4:latest

      - name: Build and push CreditBureau image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/creditbureau:latest ./creditbureau
          docker push ${{ secrets.DOCKER_USERNAME }}/creditbureau:latest

      - name: Build and push LoanBroker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/loanbroker:latest ./loan-broker
          docker push ${{ secrets.DOCKER_USERNAME }}/loanbroker:latest

      - name: Deploy services with Docker Compose
        run: |
          docker-compose up -d
